name = "falcon-logs"
main = "worker.js"
compatibility_date = "2026-05-01"

{
  "d1_databases": [
    {
      "binding": "falcon_db",
      "database_name": "falcon-db",
      "database_id": "ff585f7b-cc0e-4679-ab96-ca2ca9391e39"
    }
  ]
}
